services:
  - type: web
    name: roteiro-dispersacao-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements_light.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ASTRA_DB_TOKEN
        sync: false
      - key: ASTRA_DB_ENDPOINT
        sync: false
      - key: ASTRA_DB_KEYSPACE
        value: roteiro_dispersacao_bot
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: LANGFLOW_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /health
    
  - type: web
    name: roteiro-dispersacao-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements_light.txt
    startCommand: streamlit run streamlit_app_friendly.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BACKEND_URL
        value: https://roteiro-dispersacao-backend.onrender.com
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ASTRA_DB_TOKEN
        sync: false
      - key: ASTRA_DB_ENDPOINT
        sync: false
      - key: ASTRA_DB_KEYSPACE
        value: roteiro_dispersacao_bot

